# MSIN0093 Business Strategy and Analytics 23/24

## Workbook 1 - !strategic
## Data Cleaning & EDA
## Data Extraction: 04/11/2023 - tfl-daily-cycle-hires.csv

In [212]:
import pandas as pd
from IPython.display import display

In [213]:
fileMay1 = '/project/368JourneyDataExtract01May2023-07May2023.csv'
fileMay2 = '/project/369JourneyDataExtract08May2023-14May2023.csv'
fileMay3 = '/project/370JourneyDataExtract15May2023-21May2023.csv'
fileMay4 = '/project/371JourneyDataExtract22May2023-28May2023.csv'
fileMay5 = '/project/372JourneyDataExtract29May2023-04Jun2023.csv'

filesMay = [fileMay1, fileMay2, fileMay3, fileMay4, fileMay5]

# Initialise an empty list to store the dataframes
dfs = []

# Convert to dataframes
for file in filesMay:
    df = pd.read_csv(file)
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)

In [214]:
# Convert the 'End date' to datetime
merged_df['End date'] = pd.to_datetime(merged_df['End date'])

# Perform filtering
filtered_df = merged_df.loc[merged_df['End date'] <= '2023-05-31 23:59']

# Drop unnecessary columns
filtered_df = filtered_df.drop(columns=['Bike number', 'Bike model', 'Total duration'])

# Rename columns for clarity
filtered_df = filtered_df.rename(columns={'Number': 'rental_id', 'Start date': 'start_date', 
                                          'Start station number': 'start_station_id', 
                                          'Start station': 'start_station_name', 
                                          'End date': 'end_date', 'End station number': 'end_station_id', 
                                          'End station': 'end_station_name', 'Total duration (ms)': 'duration'})

print(filtered_df.head())

   rental_id        start_date  start_station_id  \
0  130408006  2023-05-07 23:59              1083
1  130408007  2023-05-07 23:59              1220
2  130408008  2023-05-07 23:59              1033
3  130408010  2023-05-07 23:59            200230
4  130408011  2023-05-07 23:59            300028

                start_station_name            end_date  end_station_id  \
0    Commercial Street, Shoreditch 2023-05-08 00:03:00            1102
1  Imperial College, Knightsbridge 2023-05-08 00:11:00          200116
2    Paddington Street, Marylebone 2023-05-08 00:07:00            1173
3          Maplin Street, Mile End 2023-05-08 00:03:00          200038
4        Everington Street, Fulham 2023-05-08 00:02:00          300028

                end_station_name  duration
0          Leman Street, Aldgate    248037
1  Vereker Road, West Kensington    721024
2  Gloucester Terrace, Bayswater    488052
3             Ackroyd Drive, Bow    205861
4      Everington Street, Fulham    164024

In [215]:
### BOROUGH DATA ###
borough_data = {
    'Borough': ['Westminster', 'Kensington and Chelsea', 'Camden', 'Islington', 'Greenwich', 'Tower Hamlets', 'Hackney', 'Southwark', 'Lambeth', 'Wandsworth', 'Hammersmith and Fulham', 'Newham'],
    'Districts': [
        ['Westminster', 'Hyde Park', "St. John's Wood", 'Bayswater', 'Kensington Gardens', 'Mayfair', 'Covent Garden', 'Belgravia', 'Pimlico', 'Victoria', "St. James's", 'Strand', 'Soho', 'Paddington', 'Marylebone', 'Maida Vale', "St.John's Wood"],
        ['Kensington', 'Chelsea', 'West Chelsea', 'West End', 'Ladbroke Grove', 'Sloane Square', 'Holland Park', 'Knightsbridge', 'Notting Hill', "Earl's Court", 'Portobello', 'South Kensington', 'North Kensington'],
        ['Camden Town', 'Euston', " The Regent's Park", "The Regent's Park", 'Fitzrovia', 'Somers Town', 'Bloomsbury', 'Kings Cross', 'Hampstead', 'Holborn'],
        ['Islington', "St. Luke's", 'St Lukes', 'Clerkenwell', 'Finsbury', "King's Cross", 'Angel', 'Farringdon', 'Highbury', 'Finsbury Park', 'Moorgate'],
        ['Greenwich', 'Woolwich', 'Blackheath', 'Charlton'],
        ['Canary Wharf', 'Whitechapel', 'Tower', 'Shadwell', 'Poplar', 'Barbican', 'Stepney', 'Old Ford', 'Limehouse', 'Bow', 'Cubitt Town', 'Victoria Park', 'Wapping', 'Blackwall', 'Bethnal Green', 'Mile End', 'Aldgate', 'Millwall'],
        ['Hackney', 'Hackney Wick', 'Haggerston', 'De Beauvoir Town', 'Shoreditch', 'Dalston', 'Hoxton', 'Pitfield Street North,Hoxton', 'Hackney Central'],
        ['Southwark', 'Shad Thames', 'Walworth', 'Avondale', 'Elephant & Castle', 'Rotherhithe', 'London Bridge', 'Bermondsey', 'Peckham', 'Bankside'],
        ['Lambeth', 'Waterloo', 'Vauxhall', 'Kennington', 'Oval', 'Wandsworth Road', 'Brixton', 'Clapham', 'Streatham', 'Stockwell', 'South Bank'],
        ['Wandsworth', 'Nine Elms', 'Battersea Park', 'Battersea', 'East Putney', 'Clapham Common', 'Wandsworth Common', 'Clapham Junction', 'Balham', 'Putney'],
        ['Hammersmith', 'Fulham', 'Walham Green', 'Olympia', 'Brook Green', 'Sands End', 'West Kensington', 'West Brompton', 'Parsons Green', "Parson's Green", 'White City', "Shepherd's Bush", "Westfield Southern Terrace ,Shepherd's Bush"],
        #['Liverpool Street', 'St Pauls', "St. Paul's", 'Bank', 'Monument', 'Temple', 'Guildhall'],
        ['Stratford', 'Queen Elizabeth Olympic Park']
    ]
}

boroughs_df = pd.DataFrame(borough_data)
print(boroughs_df)

                   Borough                                          Districts
0              Westminster  [Westminster, Hyde Park, St. John's Wood, Bays...
1   Kensington and Chelsea  [Kensington, Chelsea, West Chelsea, West End, ...
2                   Camden  [Camden Town, Euston,  The Regent's Park, The ...
3                Islington  [Islington, St. Luke's, St Lukes, Clerkenwell,...
4                Greenwich        [Greenwich, Woolwich, Blackheath, Charlton]
5            Tower Hamlets  [Canary Wharf, Whitechapel, Tower, Shadwell, P...
6                  Hackney  [Hackney, Hackney Wick, Haggerston, De Beauvoi...
7                Southwark  [Southwark, Shad Thames, Walworth, Avondale, E...
8                  Lambeth  [Lambeth, Waterloo, Vauxhall, Kennington, Oval...
9               Wandsworth  [Wandsworth, Nine Elms, Battersea Park, Batter...
10  Hammersmith and Fulham  [Hammersmith, Fulham, Walham Green, Olympia, B...
11                  Newham          [Stratford, Queen Elizabeth Olympic Park]

In [216]:
# Flatten the borough and district lists and create a mapping dictionary
district_to_borough = {}
for borough, districts in zip(borough_data['Borough'], borough_data['Districts']):
    for district in districts:
        district_to_borough[district] = borough

# Function to extract district from station name and map to borough
def get_borough(start_station_name):
    # Splitting on ', ' and taking the last element
    district = start_station_name.split(', ')[-1]
    # 'Unknown' if district not found
    return district_to_borough.get(district, 'Unknown')  

# Create new column 'borough'
filtered_df['borough'] = filtered_df['start_station_name'].apply(get_borough)

# Filter unknown rows
filtered_df = filtered_df.loc[~filtered_df['borough'].isin(['Unknown'])]
print(filtered_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 773397 entries, 0 to 927845
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rental_id           773397 non-null  int64
 1   start_date          773397 non-null  object
 2   start_station_id    773397 non-null  int64
 3   start_station_name  773397 non-null  object
 4   end_date            773397 non-null  datetime64[ns]
 5   end_station_id      773397 non-null  int64
 6   end_station_name    773397 non-null  object
 7   duration            773397 non-null  int64
 8   borough             773397 non-null  object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 59.0+ MB
None

# Normalisation

In [217]:
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Filter out the outliers
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

# Apply the function to the 'revenue', 'roi', and 'budget' columns
filtered_df = remove_outliers(filtered_df, 'duration')

print(filtered_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 722682 entries, 0 to 927845
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rental_id           722682 non-null  int64
 1   start_date          722682 non-null  object
 2   start_station_id    722682 non-null  int64
 3   start_station_name  722682 non-null  object
 4   end_date            722682 non-null  datetime64[ns]
 5   end_station_id      722682 non-null  int64
 6   end_station_name    722682 non-null  object
 7   duration            722682 non-null  int64
 8   borough             722682 non-null  object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 55.1+ MB
None

# Aggregation station level

In [218]:
grouped_df = filtered_df.groupby(['start_station_id', 'borough']).agg({'duration': ['count', 'mean']}).reset_index()
grouped_df.columns = ['station_id', 'borough', 'hires', 'avg_duration']
grouped_df['avg_duration'] = round((grouped_df['avg_duration']/60000),2)

# Data Quality Checks

In [219]:
valid_boroughs = ['Westminster', 'Kensington and Chelsea', 'Camden', 'Islington', 'Greenwich', 
                  'Tower Hamlets', 'Hackney', 'Southwark', 'Lambeth', 'Wandsworth', 
                  'Hammersmith and Fulham', 'Newham']

# Perform data quality checks
def check_data_quality(df):
    errors = []
    
    # Check if 'hires' are positive and integers
    if not df['hires'].apply(lambda x: x > 0 and isinstance(x, int)).all():
        errors.append("Hires column contains non-positive values or non-integer values.")
    
    # Check if 'avg_duration' are positive and floats
    if not df['avg_duration'].apply(lambda x: x > 0 and isinstance(x, float)).all():
        errors.append("Avg_duration column contains non-positive values or non-float values.")

    # Check if 'station_id' is unique
    if not df['station_id'].is_unique:
        errors.append("Station_id column is not unique.")

    # Check if 'borough' is in inner London
    if not df['borough'].isin(valid_boroughs).all():
        errors.append("Borough column contains invalid entries.")

    return errors

# Perform the checks on grouped_df
data_quality_errors = check_data_quality(grouped_df)
data_quality_errors

[]

# Create Demografic DataFrames

In [220]:
occupation_df = pd.read_csv('/project/data_new/Data_OCCUPATION_AGE_UNIT.csv')

occupation_types = set()
for col in occupation_df.columns[1:]:
    occupation_type = " - ".join(col.split(" - ")[2:-1])
    occupation_types.add(occupation_type)

# Creating a new DataFrame to store the aggregated sums
aggregated_df = pd.DataFrame()

occupation_sums = {}
for i in range(1, 10):  # 9 occupation types
    occupation = f"Occupation : {i}."
    selected_columns = [col for col in occupation_df.columns if occupation in col]
    occupation_df[f"occupation_{i}"] = occupation_df[selected_columns].sum(axis=1)

# Dropping original occupation columns
columns_to_drop = occupation_df.columns[1:-9]
occupation_df.drop(columns=columns_to_drop, inplace=True)

occupation_df.head()

,borough,occupation_1,occupation_2,occupation_3,occupation_4,occupation_5,occupation_6,occupation_7,occupation_8,occupation_9
0,Camden,15590,35083,23947,9289,4728,6150,5993,2426,6962
1,Hackney,11477,29734,25954,10995,7598,8899,8197,4014,12183
2,Hammersmith and Fulham,14622,27039,22124,9659,5471,6518,5448,2538,6729
3,Haringey,12635,29820,21650,11885,10979,9585,8565,4913,14813
4,Islington,12324,33474,23643,9727,5479,6176,6082,2925,7425

In [221]:
car_df = pd.read_csv('/project/data_new/Data_CARVAN_UNIT.csv')

renamed_columns = {
    'Car or van availability : Total\ Car or van availability - Unit : Cars or vans': 'total_cars_vans',
}

# Apply renaming
car_df.rename(columns=renamed_columns, inplace=True)

car_df.head()

                  borough  total_cars_vans
0                  Camden            46601
1                 Hackney            41800
2  Hammersmith and Fulham            43843
3                Haringey            61515
4               Islington            38629

In [222]:
sex_df = pd.read_csv('/project/data_new/Data_SEX_AGE_UNIT.csv')

# Define the age groups
age_groups_corrected = {
    '0_4': '0_15', '5_9': '0_15', '10_14': '0_15', '15': '0_15',
    '16': '16_24', '17': '16_24', '18': '16_24', '19': '16_24', '20_24': '16_24',
    '25_29': '25_49', '30_34': '25_49', '35_39': '25_49', '40_44': '25_49', '45_49': '25_49',
    '50_54': '50_64', '55_59': '50_64', '60_64': '50_64',
    '65_and_over': '65_over'
}

labels = list(set(age_groups_corrected.values()))

# Initialise columns for each bin and gender for each borough in sex_df
for label in labels:
    sex_df[f"{label}_total"] = 0
    sex_df[f"{label}_males"] = 0
    sex_df[f"{label}_females"] = 0

# Perform the aggregation into the new bins, grouped by borough
for col in sex_df.columns:
    # Skip the borough column for aggregation
    if col == 'borough':
        continue
    
    # Split column name to extract age range and gender
    parts = col.split(' - ')
    if len(parts) == 3:
        age_part, sex_part, _ = parts
        age_key = '65_and_over' if '65 and over' in age_part.lower() else age_part.split(':')[1].strip().lower().replace('age ', '').replace(' to ', '_').replace('and over', 'over')
        bin_key = age_groups_corrected.get(age_key)

        sex_key = sex_part.split(':')[1].strip().lower().replace('total\\ sex', 'total')
        if bin_key and sex_key in ['total', 'males', 'females']:
            sex_df[f"{bin_key}_{sex_key}"] += sex_df[col]

# Drop old columns except for the borough column
columns_to_drop = [col for col in sex_df.columns if 'Age :' in col]
sex_df.drop(columns=columns_to_drop, inplace=True)

# Lowercasing column names
sex_df.columns = ['borough' if col == 'borough' else col.lower() for col in sex_df.columns]

sex_df.head()

,borough,25_49_total,25_49_males,25_49_females,0_15_total,0_15_males,0_15_females,65_over_total,65_over_males,65_over_females,50_64_total,50_64_males,50_64_females,16_24_total,16_24_males,16_24_females
0,Camden,98740,49158,49582,35465,18050,17415,23977,10503,13474,29575,14802,14773,32581,15372,17209
1,Hackney,117741,59228,58513,51125,25852,25273,17395,8048,9347,27652,13566,14086,32357,15335,17022
2,Hammersmith and Fulham,90294,44346,45948,29630,14925,14705,16413,7164,9249,22511,10616,11895,23645,11863,11782
3,Haringey,117076,59229,57847,52070,26580,25490,22369,9993,12376,33272,15423,17849,30139,14999,15140
4,Islington,100544,50487,50057,32825,16714,16111,18036,8103,9933,25302,12253,13049,29418,13848,15570

In [223]:
travel_to_work_df = pd.read_csv('/project/data_new/Data_AGE_MTTWRK_UNIT.csv')

renamed_travel_to_work_columns = {
    'Travel to place of work; means of Bicycle(unit person)': 'no_bike_work_commute',
}

# Apply renaming
travel_to_work_df.rename(columns=renamed_travel_to_work_columns, inplace=True)

travel_to_work_df.head()

                  borough  no_bike_work_commute
0                  Camden                  7072
1                 Hackney                 17312
2  Hammersmith and Fulham                  7420
3                Haringey                  6142
4               Islington                 10204

In [224]:
# Merge all datasets on the 'borough' column
demo_df = car_df.merge(occupation_df, on='borough')
demo_df = demo_df.merge(sex_df, on='borough')
demo_df = demo_df.merge(travel_to_work_df, on= 'borough')

demo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 0 to 12
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   borough               13 non-null     object
 1   total_cars_vans       13 non-null     int64
 2   occupation_1          13 non-null     int64
 3   occupation_2          13 non-null     int64
 4   occupation_3          13 non-null     int64
 5   occupation_4          13 non-null     int64
 6   occupation_5          13 non-null     int64
 7   occupation_6          13 non-null     int64
 8   occupation_7          13 non-null     int64
 9   occupation_8          13 non-null     int64
 10  occupation_9          13 non-null     int64
 11  25_49_total           13 non-null     int64
 12  25_49_males           13 non-null     int64
 13  25_49_females         13 non-null     int64
 14  0_15_total            13 non-null     int64
 15  0_15_males            13 non-null     int64
 16  0_15_females          13 non-null     int64
 17  65_over_total         13 non-null     int64
 18  65_over_males         13 non-null     int64
 19  65_over_females       13 non-null     int64
 20  50_64_total           13 non-null     int64
 21  50_64_males           13 non-null     int64
 22  50_64_females         13 non-null     int64
 23  16_24_total           13 non-null     int64
 24  16_24_males           13 non-null     int64
 25  16_24_females         13 non-null     int64
 26  no_bike_work_commute  13 non-null     int64
dtypes: int64(26), object(1)
memory usage: 2.8+ KB

# Merge Demografic and TfL data

In [225]:
#Join Demografical data
demo_df['borough'] = demo_df['borough'].replace("City of London, Westminster", "Westminster")

full_df = grouped_df.merge(demo_df, on='borough', how='left')
full_df.head(12)

,station_id,borough,hires,avg_duration,total_cars_vans,occupation_1,occupation_2,occupation_3,occupation_4,occupation_5,...,65_over_total,65_over_males,65_over_females,50_64_total,50_64_males,50_64_females,16_24_total,16_24_males,16_24_females,no_bike_work_commute
0,959,Lambeth,912,12.82,66791,18256,42956,33686,16892,10764,...,23187,10273,12914,35985,17622,18363,37805,18448,19357,13455
1,962,Lambeth,984,13.52,66791,18256,42956,33686,16892,10764,...,23187,10273,12914,35985,17622,18363,37805,18448,19357,13455
2,963,Southwark,1034,14.22,60438,15620,38136,25710,14616,9704,...,22329,9707,12622,36226,17881,18345,39978,18972,21006,10898
3,964,Islington,1236,11.84,38629,12324,33474,23643,9727,5479,...,18036,8103,9933,25302,12253,13049,29418,13848,15570,10204
4,965,Westminster,922,13.45,50502,23372,31830,26473,10163,4425,...,25549,11931,13618,32195,15752,16443,26620,13128,13492,5617
5,967,Tower Hamlets,938,11.68,43589,13310,31093,24699,11964,7277,...,15570,7107,8463,23422,12110,11312,42781,20888,21893,8112
6,968,Westminster,1456,17.59,50502,23372,31830,26473,10163,4425,...,25549,11931,13618,32195,15752,16443,26620,13128,13492,5617
7,969,Camden,856,13.61,46601,15590,35083,23947,9289,4728,...,23977,10503,13474,29575,14802,14773,32581,15372,17209,7072
8,970,Camden,755,13.95,46601,15590,35083,23947,9289,4728,...,23977,10503,13474,29575,14802,14773,32581,15372,17209,7072
9,972,Camden,1241,12.27,46601,15590,35083,23947,9289,4728,...,23977,10503,13474,29575,14802,14773,32581,15372,17209,7072
10,973,Hackney,2537,13.85,41800,11477,29734,25954,10995,7598,...,17395,8048,9347,27652,13566,14086,32357,15335,17022,17312
11,974,Camden,1231,13.87,46601,15590,35083,23947,9289,4728,...,23977,10503,13474,29575,14802,14773,32581,15372,17209,7072

# Add extra KPIs

In [226]:
def summ(num1, *args):
    total = num1
    for num in args:
        total = total + num
    return total

In [227]:
full_df['total_persons'] = summ(full_df['0_15_total'], full_df['16_24_total'], full_df['25_49_total'],
                                full_df['50_64_total'], full_df['65_over_total'])
full_df['hired_min_per_100k'] = round(full_df['hires'] * full_df['avg_duration']/(full_df['total_persons'])*100000,2)
full_df['male_percentage'] = round(100*summ(full_df['0_15_males'], full_df['16_24_males'], full_df['25_49_males'],
                                full_df['50_64_males'], full_df['65_over_males'])/full_df['total_persons'],2)
full_df['total_workforce'] = summ(full_df['occupation_1'], full_df['occupation_2'], full_df['occupation_3'],
                                full_df['occupation_4'], full_df['occupation_5'], full_df['occupation_6'], 
                                  full_df['occupation_7'], full_df['occupation_8'], full_df['occupation_9'])
full_df['bike_commuters_per_100k'] = round(full_df['no_bike_work_commute']/(full_df['total_persons'])*100000,2)
full_df['cars_per_100k'] = round(full_df['total_cars_vans']/(full_df['total_persons'])*100000,2)

station_counts = full_df.groupby('borough')['station_id'].nunique()
full_df['total_stations'] = full_df['borough'].map(station_counts)
full_df['total_stations_per_100k'] = round(full_df['total_stations']/(full_df['total_persons'])*100000,2)
full_df.head(12)

,station_id,borough,hires,avg_duration,total_cars_vans,occupation_1,occupation_2,occupation_3,occupation_4,occupation_5,...,16_24_females,no_bike_work_commute,total_persons,hired_min_per_100k,male_percentage,total_workforce,bike_commuters_per_100k,cars_per_100k,total_stations,total_stations_per_100k
0,959,Lambeth,912,12.82,66791,18256,42956,33686,16892,10764,...,19357,13455,303086,3857.60,49.79,167205,4439.33,22036.98,62,20.46
1,962,Lambeth,984,13.52,66791,18256,42956,33686,16892,10764,...,19357,13455,303086,4389.41,49.79,167205,4439.33,22036.98,62,20.46
2,963,Southwark,1034,14.22,60438,15620,38136,25710,14616,9704,...,21006,10898,288283,5100.36,49.47,147995,3780.31,20964.82,49,17.00
3,964,Islington,1236,11.84,38629,12324,33474,23643,9727,5479,...,15570,10204,206125,7099.69,49.20,107255,4950.39,18740.57,46,22.32
4,965,Westminster,922,13.45,50502,23372,31830,26473,10163,4425,...,13492,5617,226771,5468.47,50.99,117303,2476.95,22270.04,153,67.47
5,967,Tower Hamlets,938,11.68,43589,13310,31093,24699,11964,7277,...,21893,8112,254096,4311.69,51.52,121244,3192.49,17154.54,117,46.05
6,968,Westminster,1456,17.59,50502,23372,31830,26473,10163,4425,...,13492,5617,226771,11293.79,50.99,117303,2476.95,22270.04,153,67.47
7,969,Camden,856,13.61,46601,15590,35083,23947,9289,4728,...,17209,7072,220338,5287.40,48.96,110168,3209.61,21149.78,71,32.22
8,970,Camden,755,13.95,46601,15590,35083,23947,9289,4728,...,17209,7072,220338,4780.04,48.96,110168,3209.61,21149.78,71,32.22
9,972,Camden,1241,12.27,46601,15590,35083,23947,9289,4728,...,17209,7072,220338,6910.78,48.96,110168,3209.61,21149.78,71,32.22
10,973,Hackney,2537,13.85,41800,11477,29734,25954,10995,7598,...,17022,17312,246270,14267.86,49.55,119051,7029.68,16973.24,40,16.24
11,974,Camden,1231,13.87,46601,15590,35083,23947,9289,4728,...,17209,7072,220338,7748.99,48.96,110168,3209.61,21149.78,71,32.22

# Export

In [228]:
full_df.to_csv("/project/station_demo_data.csv", index=False)